# Generated by Django 4.2.4 on 2023-08-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_categories'),
    ]

    operations = [
    ]
